import { Product, Customer, Translation, Employee } from './types';

// No initial data - stores start empty
// Only walk-in customer is created dynamically for each store
// Categories are now dynamic and stored in Firebase

// Firebase Hosting URL for public invoice access
// In production, this would be your Firebase Hosting URL
// Example: https://your-project-id.web.app or https://your-domain.com
export const PUBLIC_INVOICE_BASE_URL = import.meta.env.VITE_PUBLIC_INVOICE_URL || 'https://inventoryinvoice.labinitial.com';

export const TRANSLATIONS: Translation = {
  welcome: { en: 'Welcome to Raad Laundry', bn: 'Raad Laundry অ্যাপে স্বাগতম' },
  login: { en: 'Login', bn: 'লগইন' },
  signup: { en: 'Sign Up', bn: 'সাইন আপ' },
  dashboard: { en: 'Dashboard', bn: 'ড্যাশবোর্ড' },
  pos: { en: 'POS', bn: 'POS' },
  customers: { en: 'Customers', bn: 'গ্রাহক' },
  products: { en: 'Products/Services', bn: 'পণ্য/সেবা' },
  reports: { en: 'Reports & AI', bn: 'রিপোর্ট এবং এআই' },
  invoices: { en: 'Invoices', bn: 'চালান' },
  settings: { en: 'Settings', bn: 'সেটিংস' },
  employees: { en: 'Employees', bn: 'কর্মচারী' },
  add_product: { en: 'Add Product', bn: 'পণ্য যোগ করুন' },
  name: { en: 'Name', bn: 'নাম' },
  price: { en: 'Price', bn: 'দাম' },
  category: { en: 'Category', bn: 'বিভাগ' },
  stock: { en: 'Stock', bn: 'স্টক' },
  vat: { en: 'VAT (%)', bn: 'ভ্যাট (%)' },
  unit: { en: 'Unit', bn: 'একক' },
  save: { en: 'Save', bn: 'সংরক্ষণ' },
  cancel: { en: 'Cancel', bn: 'বাতিল' },
  confirm_order: { en: 'Confirm Order', bn: 'অর্ডার নিশ্চিত করুন' },
  total: { en: 'Total', bn: 'মোট' },
  search: { en: 'Search...', bn: 'অনুসন্ধান...' },
  select_customer: { en: 'Select Customer', bn: 'গ্রাহক নির্বাচন করুন' },
  walk_in: { en: 'Walk-in Customer', bn: 'সাধারণ ক্রেতা' },
  invoice: { en: 'INVOICE', bn: 'চালান' },
  print: { en: 'Print', bn: 'প্রিন্ট' },
  close: { en: 'Close', bn: 'বন্ধ করুন' },
  ai_insight: { en: 'Ask AI for Insights', bn: 'এআই ইনসাইট দেখুন' },
  business_name: { en: 'Business Name', bn: 'ব্যবসার নাম' },
  address: { en: 'Address', bn: 'ঠিকানা' },
  phone: { en: 'Phone', bn: 'ফোন' },
  logout: { en: 'Logout', bn: 'লগআউট' },
  select_lang: { en: 'Select Language', bn: 'ভাষা নির্বাচন করুন' },
  enter_software: { en: 'Enter Cost Estimation App', bn: 'এস্টিমেশন অ্যাপে প্রবেশ করুন' },
  software_hub: { en: 'Software Hub', bn: 'সফটওয়্যার হাব' },
  home_desc: { en: 'Manage your business efficiently with our suite of tools.', bn: 'আমাদের টুলস ব্যবহার করে আপনার ব্যবসা দক্ষতার সাথে পরিচালনা করুন।' },
  discount: { en: 'Discount', bn: 'ছাড়' },
  paid_amount: { en: 'Paid Amount', bn: 'পরিশোধিত অর্থ' },
  due_amount: { en: 'Due Amount', bn: 'বকেয়া' },
  quick_add_customer: { en: 'Quick Add Customer', bn: 'দ্রুত গ্রাহক যোগ করুন' },
  pay_due: { en: 'Pay Due', bn: 'বকেয়া পরিশোধ' },
  payment_proof: { en: 'Payment Proof/Ref', bn: 'পেমেন্ট প্রমাণ/রেফারেন্স' },
  receive_payment: { en: 'Receive Payment', bn: 'পেমেন্ট গ্রহণ করুন' },
  current_due: { en: 'Current Due', bn: 'বর্তমান বকেয়া' },
  change_return: { en: 'Change', bn: 'ফেরত' },
  thank_you: { en: 'Thank you for your business!', bn: 'আমাদের সাথে থাকার জন্য ধন্যবাদ!' },
  image: { en: 'Image', bn: 'ছবি' },
  upload_image: { en: 'Upload Image', bn: 'ছবি আপলোড করুন' },
  status: { en: 'Status', bn: 'অবস্থা' },
  payment_status: { en: 'Payment Status', bn: 'পেমেন্ট অবস্থা' },
  all: { en: 'All', bn: 'সব' },
  paid: { en: 'Paid', bn: 'পরিশোধিত' },
  unpaid: { en: 'Unpaid', bn: 'বকেয়া' },
  delivered: { en: 'Delivered', bn: 'সরবরাহকৃত' },
  pending: { en: 'Pending', bn: 'অপেক্ষমাণ' },
  collected: { en: 'Collected', bn: 'সংগৃহীত' },
  product_view: { en: 'Product View', bn: 'পণ্য প্রদর্শন' },
  grid_view: { en: 'Grid View', bn: 'গ্রিড ভিউ' },
  list_view: { en: 'List View', bn: 'লিস্ট ভিউ' },
  manage_employee: { en: 'Manage Employees', bn: 'কর্মচারী ব্যবস্থাপনা' },
  new_employee: { en: 'New Employee', bn: 'নতুন কর্মচারী' },
  attendance: { en: 'Attendance', bn: 'হাজিরা' },
  salary: { en: 'Salary', bn: 'বেতন' },
  designation: { en: 'Designation', bn: 'পদবি' },
  join_date: { en: 'Join Date', bn: 'যোগদানের তারিখ' },
  present: { en: 'Present', bn: 'উপস্থিত' },
  absent: { en: 'Absent', bn: 'অনুপস্থিত' },
  half_day: { en: 'Half Day', bn: 'অর্ধ দিবস' },
  leave: { en: 'Leave', bn: 'ছুটি' },
  pay_salary: { en: 'Pay Salary', bn: 'বেতন প্রদান' },
  mark_all_present: { en: 'Mark All Present', bn: 'সবাইকে উপস্থিত চিহ্নিত করুন' },
  employee_reports: { en: 'Reports', bn: 'রিপোর্ট' },
  attendance_summary: { en: 'Attendance Summary', bn: 'হাজিরা সারাংশ' },
  salary_statement: { en: 'Salary Statement', bn: 'বেতন বিবরণী' },
  total_paid: { en: 'Total Paid', bn: 'মোট পরিশোধিত' },
  currency: { en: 'Currency', bn: 'মুদ্রা' },
  categories: { en: 'Categories', bn: 'বিভাগ' },
  roles: { en: 'Roles', bn: 'ভূমিকা' },
  stockHistory: { en: 'Stock History', bn: 'স্টক ইতিহাস' },
  today: { en: 'Today', bn: 'আজ' },
  week: { en: 'This Week', bn: 'এই সপ্তাহ' },
  month: { en: 'This Month', bn: 'এই মাস' },
  custom: { en: 'Custom Range', bn: 'কাস্টম রেঞ্জ' },
  insights: { en: 'Insights', bn: 'ইনসাইটস' },
  detailed_analysis: { en: 'Detailed Analysis', bn: 'বিস্তারিত বিশ্লেষণ' },
  sales_ledger: { en: 'Sales Ledger', bn: 'বিক্রয় খতিয়ান' },
  customer_report: { en: 'Customer Report', bn: 'গ্রাহক রিপোর্ট' },
  gross_sales: { en: 'Gross Sales', bn: 'মোট বিক্রয়' },
  gross_profit: { en: 'Gross Profit', bn: 'মোট লাভ' },
  profit_margin: { en: 'Profit Margin', bn: 'লাভ মার্জিন' },
  net_sales: { en: 'Net Sales', bn: 'নিট বিক্রয়' },
  cost_of_goods: { en: 'Cost of Goods', bn: 'পণ্যের খরচ' },
  recurring_profit: { en: 'Recurring Profit', bn: 'পুনরাবৃত্ত লাভ' },
  cash: { en: 'Cash', bn: 'নগদ' },
  card: { en: 'Card', bn: 'কার্ড' },
  pay_later: { en: 'Pay Later', bn: 'পরে প্রদান' },
  sl_no: { en: 'SL No', bn: 'ক্রমিক নং' },
  product_name: { en: 'Product Name', bn: 'পণ্যের নাম' },
  purchase_price: { en: 'Purchase Price', bn: 'ক্রয় মূল্য' },
  selling_price: { en: 'Selling Price', bn: 'বিক্রয় মূল্য' },
  profit_per_unit: { en: 'Profit per Unit', bn: 'প্রতি ইউনিট লাভ' },
  profit_percent: { en: 'Profit %', bn: 'লাভ %' },
  selling_qty: { en: 'Selling Qty', bn: 'বিক্রয় পরিমাণ' },
  total_profit: { en: 'Total Profit', bn: 'মোট লাভ' },
  date: { en: 'Date', bn: 'তারিখ' },
  total_purchases: { en: 'Total Purchases', bn: 'মোট ক্রয়' },
  items_purchased: { en: 'Items Purchased', bn: 'ক্রয়কৃত আইটেম' },
  copy_numbers: { en: 'Copy Numbers', bn: 'নম্বর কপি করুন' },
};
